In [2]:
import pandas as pd
import numpy as np

In [10]:
dates = pd.date_range("20130101", periods=100)

In [11]:
df = pd.DataFrame(dates)

In [16]:
df.head(n=10)

           0
0 2013-01-01
1 2013-01-02
2 2013-01-03
3 2013-01-04
4 2013-01-05
5 2013-01-06
6 2013-01-07
7 2013-01-08
8 2013-01-09
9 2013-01-10

In [3]:
vec = np.arange(20)

In [4]:
vec

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [5]:
vec = vec + 3

In [6]:
vec

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22])

In [9]:
with open("..\data\ex1.csv","r") as f:
    print(f.read())

a,b,c,d,message,
1,2,3,4,hello,
5,6,7,8,world
9,10,11,12,foo

In [10]:
fpath = "..\data\ex1.csv"
df = pd.read_csv(fpath)
df

   a   b   c   d message  Unnamed: 5
0  1   2   3   4   hello         NaN
1  5   6   7   8   world         NaN
2  9  10  11  12     foo         NaN

In [11]:
# json string                                                                                                                
s = '''{
    "col1": {
        "row1":1,
        "row2":2,
        "row3":3
    },
    "col2":{
        "row1":"x",
        "row2":"y",
        "row3":"z"
    }
}'''

In [14]:
from io import StringIO
df = pd.read_json(StringIO(s))

In [15]:
df

      col1 col2
row1     1    x
row2     2    y
row3     3    z

In [16]:
# Przykładowy zagnieżdżony JSON jako string
json_data = '''[
    {
        "name": "Alice",
        "age": 25,
        "address": {
            "street": "123 Main St",
            "city": "Wonderland"
        },
        "hobbies": ["reading", "gardening"]
    },
    {
        "name": "Bob",
        "age": 30,
        "address": {
            "street": "456 Elm St",
            "city": "Builderland"
        },
        "hobbies": ["building", "cycling"]
    }
]'''

In [17]:
df = pd.read_json(StringIO(json_data))
df

,name,age,address,hobbies
0,Alice,25,"{'street': '123 Main St', 'city': 'Wonderland'}","[reading, gardening]"
1,Bob,30,"{'street': '456 Elm St', 'city': 'Builderland'}","[building, cycling]"

In [20]:
import json
data = json.loads(json_data)
df = pd.json_normalize(data)

In [21]:
df

    name  age               hobbies address.street address.city
0  Alice   25  [reading, gardening]    123 Main St   Wonderland
1    Bob   30   [building, cycling]     456 Elm St  Builderland

In [22]:
# filtrowanie

In [23]:
df = pd.DataFrame({
    'name': ['Jane', 'John', 'Ashley', 'Mike', 'Emily', 'Jack', 'Catlin'],
    'ctg': ['A', 'A', 'C', 'B', 'B', 'C', 'B'],
    'val': np.random.random(7).round(2),
    'val2': np.random.randint(1, 10, size=7)
})
df

     name ctg   val  val2
0    Jane   A  0.22     2
1    John   A  0.18     2
2  Ashley   C  0.49     4
3    Mike   B  0.63     5
4   Emily   B  0.55     2
5    Jack   C  0.78     7
6  Catlin   B  0.70     8

In [27]:
adict = {
    'name': ['Jane', 'John', 'Ashley', 'Mike', 'Emily', 'Jack', 'Catlin'],
    'ctg': ['A', 'A', 'C', 'B', 'B', 'C', 'B'],
    'val': np.random.random(7).round(2),
    'val2': np.random.randint(1, 10, size=7)
}

In [28]:
df = pd.DataFrame(adict)

In [30]:
df

     name ctg   val  val2
0    Jane   A  0.05     6
1    John   A  0.59     1
2  Ashley   C  0.28     4
3    Mike   B  0.80     1
4   Emily   B  0.27     9
5    Jack   C  0.90     1
6  Catlin   B  0.81     1

In [31]:
mask = df.val > 0.5

In [32]:
df[ mask ]

     name ctg   val  val2
1    John   A  0.59     1
3    Mike   B  0.80     1
5    Jack   C  0.90     1
6  Catlin   B  0.81     1

In [33]:
df['name']

0      Jane
1      John
2    Ashley
3      Mike
4     Emily
5      Jack
6    Catlin
Name: name, dtype: object

In [36]:
names = ['Jane','Ashley','Jack']
mask = df['name'].isin(names)
df[ mask ]

     name ctg   val  val2
0    Jane   A  0.05     6
2  Ashley   C  0.28     4
5    Jack   C  0.90     1

In [37]:
# grupowanie

In [41]:

cols = ["first_name", "last_name", 'type', 'state', 'party', 'gender', 'birthday']

df = pd.read_csv(
    '../data/legislators-historical.csv', 
    usecols=cols,
    parse_dates=['birthday'],
    dtype={
        "state": "category",
        "type": "category",
        "party": "category",
        "gender": "category",
        "first_name": "category"
    }
)
df

      last_name  first_name   birthday gender type state                party
0       Bassett     Richard 1745-04-02      M  sen    DE  Anti-Administration
1         Bland  Theodorick 1742-03-21      M  rep    VA                  NaN
2         Burke     Aedanus 1743-06-16      M  rep    SC                  NaN
3       Carroll      Daniel 1730-07-22      M  rep    MD                  NaN
4        Clymer      George 1739-03-16      M  rep    PA                  NaN
...         ...         ...        ...    ...  ...   ...                  ...
11970   Garrett      Thomas 1972-03-27      M  rep    VA           Republican
11971    Handel       Karen 1962-04-18      F  rep    GA           Republican
11972     Jones      Brenda 1959-10-24      F  rep    MI             Democrat
11973    Marino         Tom 1952-08-15      M  rep    PA           Republican
11974     Jones      Walter 1943-02-10      M  rep    NC           Republican

[11975 rows x 7 columns]

In [42]:
df['birthday'][1]

Timestamp('1742-03-21 00:00:00')

In [47]:
mask = df.state.str.startswith('A')
df = df[ mask ]
df

In [54]:
df_groupby = df.groupby('state', observed = True)
#df_groupby.count()

In [55]:
df_groupby.count()

       last_name  first_name  birthday  gender  type  party
state
AK            16          16        16      16    16     14
AL           206         206       197     206   206    206
AR           117         117       114     117   117    115
AS             2           2         2       2     2      2
AZ            48          48        48      48    48     48

In [56]:
#apply

In [57]:
students = pd.Series(
    data=[180, 175, 168, 190],
    index=['Vik', 'Mehdi', 'Bella', 'Chriss']
)
students

Vik       180
Mehdi     175
Bella     168
Chriss    190
dtype: int64

In [58]:
def cm_to_feet(h):
    return round(h/30.48,2)

In [59]:
cm_to_feet(10)

0.33

In [60]:
cm_to_feet(students)

Vik       5.91
Mehdi     5.74
Bella     5.51
Chriss    6.23
dtype: float64

In [61]:
students.apply(cm_to_feet)

Vik       5.91
Mehdi     5.74
Bella     5.51
Chriss    6.23
dtype: float64

In [63]:
data = pd.DataFrame({
    'EmployeeName': ['Callen Dunkley', 'Sarah Rayner', 'Jeanette Sloan', 'Kaycee Acosta', 'Henri Conroy', 'Emma Peralta', 'Martin Butt', 'Alex Jensen', 'Kim Howarth', 'Jane Burnett'],
    'Department': ['Accounting', 'Engineering', 'Engineering', 'HR', 'HR', 'HR', 'Data Science', 'Data Science', 'Accounting', 'Data Science'],
    'HireDate': [2010, 2018, 2012, 2014, 2014, 2018, 2020, 2018, 2020, 2012],
    'Sex': ['M', 'F', 'F', 'F', 'M', 'F', 'M', 'M', 'M', 'F'],
    'Birthdate': ['04/09/1982', '14/04/1981', '06/05/1997', '08/01/1986', '10/10/1988', '12/11/1992', '10/04/1991', '16/07/1995', '08/10/1992', '11/10/1979'],
    'Weight': [78, 80, 66, 67, 90, 57, 115, 87, 95, 57],
    'Height': [176, 160, 169, 157, 185, 164, 195, 180, 174, 165],
    'Kids': [2, 1, 0, 1, 1, 0, 2, 0, 3, 1]
})
data

,EmployeeName,Department,HireDate,Sex,Birthdate,Weight,Height,Kids
0,Callen Dunkley,Accounting,2010,M,04/09/1982,78,176,2
1,Sarah Rayner,Engineering,2018,F,14/04/1981,80,160,1
2,Jeanette Sloan,Engineering,2012,F,06/05/1997,66,169,0
3,Kaycee Acosta,HR,2014,F,08/01/1986,67,157,1
4,Henri Conroy,HR,2014,M,10/10/1988,90,185,1
5,Emma Peralta,HR,2018,F,12/11/1992,57,164,0
6,Martin Butt,Data Science,2020,M,10/04/1991,115,195,2
7,Alex Jensen,Data Science,2018,M,16/07/1995,87,180,0
8,Kim Howarth,Accounting,2020,M,08/10/1992,95,174,3
9,Jane Burnett,Data Science,2012,F,11/10/1979,57,165,1

In [64]:
data['Height'].apply(cm_to_feet)

0    5.77
1    5.25
2    5.54
3    5.15
4    6.07
5    5.38
6    6.40
7    5.91
8    5.71
9    5.41
Name: Height, dtype: float64

In [65]:
data['Height_in_feet'] = data['Height'].apply(cm_to_feet)
data

,EmployeeName,Department,HireDate,Sex,Birthdate,Weight,Height,Kids,Height_in_feet
0,Callen Dunkley,Accounting,2010,M,04/09/1982,78,176,2,5.77
1,Sarah Rayner,Engineering,2018,F,14/04/1981,80,160,1,5.25
2,Jeanette Sloan,Engineering,2012,F,06/05/1997,66,169,0,5.54
3,Kaycee Acosta,HR,2014,F,08/01/1986,67,157,1,5.15
4,Henri Conroy,HR,2014,M,10/10/1988,90,185,1,6.07
5,Emma Peralta,HR,2018,F,12/11/1992,57,164,0,5.38
6,Martin Butt,Data Science,2020,M,10/04/1991,115,195,2,6.40
7,Alex Jensen,Data Science,2018,M,16/07/1995,87,180,0,5.91
8,Kim Howarth,Accounting,2020,M,08/10/1992,95,174,3,5.71
9,Jane Burnett,Data Science,2012,F,11/10/1979,57,165,1,5.41

In [69]:
data['First Name'] = data['EmployeeName'].apply(lambda fullname: fullname.split()[0])
data

,EmployeeName,Department,HireDate,Sex,Birthdate,Weight,Height,Kids,Height_in_feet,First Name
0,Callen Dunkley,Accounting,2010,M,04/09/1982,78,176,2,5.77,Callen
1,Sarah Rayner,Engineering,2018,F,14/04/1981,80,160,1,5.25,Sarah
2,Jeanette Sloan,Engineering,2012,F,06/05/1997,66,169,0,5.54,Jeanette
3,Kaycee Acosta,HR,2014,F,08/01/1986,67,157,1,5.15,Kaycee
4,Henri Conroy,HR,2014,M,10/10/1988,90,185,1,6.07,Henri
5,Emma Peralta,HR,2018,F,12/11/1992,57,164,0,5.38,Emma
6,Martin Butt,Data Science,2020,M,10/04/1991,115,195,2,6.40,Martin
7,Alex Jensen,Data Science,2018,M,16/07/1995,87,180,0,5.91,Alex
8,Kim Howarth,Accounting,2020,M,08/10/1992,95,174,3,5.71,Kim
9,Jane Burnett,Data Science,2012,F,11/10/1979,57,165,1,5.41,Jane

In [70]:
data['Last Name'] = data['EmployeeName'].apply(lambda fullname: fullname.split()[1])
data

,EmployeeName,Department,HireDate,Sex,Birthdate,Weight,Height,Kids,Height_in_feet,First Name,Last Name
0,Callen Dunkley,Accounting,2010,M,04/09/1982,78,176,2,5.77,Callen,Dunkley
1,Sarah Rayner,Engineering,2018,F,14/04/1981,80,160,1,5.25,Sarah,Rayner
2,Jeanette Sloan,Engineering,2012,F,06/05/1997,66,169,0,5.54,Jeanette,Sloan
3,Kaycee Acosta,HR,2014,F,08/01/1986,67,157,1,5.15,Kaycee,Acosta
4,Henri Conroy,HR,2014,M,10/10/1988,90,185,1,6.07,Henri,Conroy
5,Emma Peralta,HR,2018,F,12/11/1992,57,164,0,5.38,Emma,Peralta
6,Martin Butt,Data Science,2020,M,10/04/1991,115,195,2,6.40,Martin,Butt
7,Alex Jensen,Data Science,2018,M,16/07/1995,87,180,0,5.91,Alex,Jensen
8,Kim Howarth,Accounting,2020,M,08/10/1992,95,174,3,5.71,Kim,Howarth
9,Jane Burnett,Data Science,2012,F,11/10/1979,57,165,1,5.41,Jane,Burnett

In [72]:
def calc_bmi(weight, height):
    return np.round(weight/(height/100)**2, 2)

In [82]:
data['BMI'] = data.apply(lambda x: calc_bmi(x['Weight'], x['Height']), axis=1)
data

,EmployeeName,Department,HireDate,Sex,Birthdate,Weight,Height,Kids,Height_in_feet,First Name,Last Name,BMI
0,Callen Dunkley,Accounting,2010,M,04/09/1982,78,176,2,5.77,Callen,Dunkley,25.18
1,Sarah Rayner,Engineering,2018,F,14/04/1981,80,160,1,5.25,Sarah,Rayner,31.25
2,Jeanette Sloan,Engineering,2012,F,06/05/1997,66,169,0,5.54,Jeanette,Sloan,23.11
3,Kaycee Acosta,HR,2014,F,08/01/1986,67,157,1,5.15,Kaycee,Acosta,27.18
4,Henri Conroy,HR,2014,M,10/10/1988,90,185,1,6.07,Henri,Conroy,26.30
5,Emma Peralta,HR,2018,F,12/11/1992,57,164,0,5.38,Emma,Peralta,21.19
6,Martin Butt,Data Science,2020,M,10/04/1991,115,195,2,6.40,Martin,Butt,30.24
7,Alex Jensen,Data Science,2018,M,16/07/1995,87,180,0,5.91,Alex,Jensen,26.85
8,Kim Howarth,Accounting,2020,M,08/10/1992,95,174,3,5.71,Kim,Howarth,31.38
9,Jane Burnett,Data Science,2012,F,11/10/1979,57,165,1,5.41,Jane,Burnett,20.94